### ISSUE TITLE
Query on how to train with question-answer pair data

### ISSUE THREAD

**Issue by kaiwen98** [google-research-datasets/NewsQuizQA#2]
I have read the paper on Arxiv, and I am really impressed by the work. I will like to implement the paper from my computer, but I am not exactly sure how the data is framed. Particularly, how does the question-answer pair fit in with the input/target text, which is the expected format?

**Comment by vqtran** [comment]
Given a a style label (e.g. "news quiz") and a (passage, question, answer) triplet we set:

Input: "Style <style_label>: <passage>"
Target: "<question> \n <answer>"

In particular "passage" is a CNN/DailyMail style summary of a news article. Hope this helps!

**Comment by kaiwen98** [comment]
@vqtran Thank you for the specification!
So I suppose it might be something like this?

Input: ```"Style newsquiz <summarised passage>" : String```
Target: ```("<question>", "<answer>") : Pair<String, String>```

May I clarify if separation tokens should be used for the target instead? In particular,
Target: ```"<question> [SEP] <answer>" : String```
?

Thank you!

**Comment by vqtran** [comment]
Oops, it looks like angle brackets in my initial comments disappeared. 

In the paper we use `Style newsquiz: <summarized passage>` and output `<question> \n <answer>`

I think the choice of the style prefix as well as the delimiter between question and answer will not affect the model performance very much, [SEP] should be fine.

**Comment by kaiwen98** [comment]
Understood. Appreciate it!
